
// src/engine/__tests__/quotients.test.ts
import { describe, it, expect } from 'vitest';
import { createSn, createCn } from '../factory';
import { createQuotientGroup } from '../quotients';

describe('Quotient Groups', () => {
    it('S_3 / A_3 should be isomorphic to Z_2', () => {
        const s3 = createSn(3);
        const subgroups = s3.getSubgroups();
        // A_3 is the unique subgroup of order 3 in S_3 (generated by (1 2 3))
        const a3 = subgroups.find(s => s.order === 3);
        expect(a3).toBeDefined();
        if (!a3) return;
        expect(a3.isNormal).toBe(true);

        const quotient = createQuotientGroup(s3, a3);
        const qProps = quotient.getProperties();

        // Order of G/N is |G|/|N| = 6/3 = 2
        expect(qProps.order).toBe(2);
        expect(qProps.isAbelian).toBe(true);
        expect(qProps.isCyclic).toBe(true);
    });

    it('Z_4 / Z_2 should be isomorphic to Z_2', () => {
        const z4 = createCn(4);
        const subgroups = z4.getSubgroups();
        // Z_2 in Z_4 is {0, 2} (order 2)
        const z2 = subgroups.find(s => s.order === 2);
        expect(z2).toBeDefined();
        if (!z2) return;

        const quotient = createQuotientGroup(z4, z2);
        const qProps = quotient.getProperties();

        expect(qProps.order).toBe(2);
        expect(qProps.isCyclic).toBe(true); // Z_4/Z_2 is Z_2
    });

    it('Quotient by full group should be trivial', () => {
        const z3 = createCn(3);
        const full = z3.getSubgroups().find(s => s.order === 3);
        if (!full) throw new Error("Full subgroup detection failed");

        const q = createQuotientGroup(z3, full);
        expect(q.getProperties().order).toBe(1);
    });

    it('Quotient by trivial group should be isomorphic to original', () => {
        const s3 = createSn(3);
        const trivial = s3.getSubgroups().find(s => s.order === 1);
        if (!trivial) throw new Error("Trivial subgroup detection failed");

        const q = createQuotientGroup(s3, trivial);
        const p = q.getProperties();
        expect(p.order).toBe(6);
        expect(p.isAbelian).toBe(false);
    });
});
