
// src/data/glossary.ts
export interface GlossaryTerm {
    term: string;
    definition: string; // Markdown/TeX supported? Simple string for now.
    example?: string;
}

export const glossaryTerms: Record<string, GlossaryTerm> = {
    'order': {
        term: 'Order',
        definition: 'The number of elements in the group, denoted by |G|.',
        example: 'For Z_4, the order is 4.'
    },
    'abelian': {
        term: 'Abelian',
        definition: 'A group is abelian if the operation is commutative: a*b = b*a for all elements.',
        example: 'Z_n is always abelian. S_3 is not.'
    },
    'cyclic': {
        term: 'Cyclic',
        definition: 'A group generated by a single element.',
        example: 'Z_4 is cyclic, generated by 1. V_4 is not cyclic.'
    },
    'simple': {
        term: 'Simple',
        definition: 'A group is simple if its only normal subgroups are the trivial subgroup and the group itself.',
        example: 'A_5 is the smallest non-abelian simple group.'
    },
    'center': {
        term: 'Center',
        definition: 'The set of elements that commute with every element of the group, denoted Z(G).',
        example: 'The center of an abelian group is the whole group.'
    },
    'subgroup': {
        term: 'Subgroup',
        definition: 'A subset of a group that is itself a group under the same operation.',
    },
    'normal': {
        term: 'Normal subgroup',
        definition: 'A subgroup N is normal if gNg^-1 = N for all g in G. Only normal subgroups can be used to form quotient groups.',
    },
    'quotient': {
        term: 'Quotient group',
        definition: 'The group formulated by the set of cosets of a normal subgroup N, denoted G/N.',
    },
    'centralizer': {
        term: 'Centralizer',
        definition: 'The complex of elements that commute with a specific element x, denoted C_G(x).',
    },
    'conjugacy class': {
        term: 'Conjugacy class',
        definition: 'The set of elements { gxg^-1 | g in G } for a given element x.',
    }
    // Add more as needed
};
